export const Grado = [
    "Abogacía",	
    "Escribanía",
    "Contador Público",
    "Lic. en Administración",
    "Lic. en Administración Agraria",
    "Lic. en Administración Hotelera",
    "Lic. en Comercio Internacional",
    "Lic. en Gestión Ambiental",
    "Lic. en Ambiente y Energías Renovables",
    "Lic. en Gestión Turística",
    "Lic. en Gestión de Recursos Humanos",
    "Lic. en Comercialización (Marketing)",
    "Lic. en Relaciones Internacionales",
    "Lic. en Administración Pública",
    "Lic. en Educación (CCC)",
    "Lic. en Relaciones Públicas e Institucionales",
    "Lic. en Informática",
    "Lic. en Periodismo",
    "Lic. en Higiene, Seguridad y Medio ambiente del Trabajo",
    "Lic. en Diseño y Animación Digital",
    "Lic. en Logística Global",
    "Lic. en Criminología y Seguridad",
    "Lic. en Publicidad",
    "Lic. en Inteligencia Artificial y Robótica",
    "Lic. en Emprendimiento -CCC",
    "Lic. en Matemática",
    "Lic. en Ciencias de Datos",
    "Lic. en Terapia Ocupacional y Desarrollo Humano",
    "Lic. en Antropología Organizacional",
    "Lic. en Seguridad Informática",
    "Lic. en Gerontología",
    "Lic. en Administración de Infraestructura Tecnológica",
    "Lic. en Ciencia Política y Gobierno",
    "Lic. en Administración de Servicios de Salud CCC",
    "Lic. en Educación y Nuevas Tecnologías",
    "Lic. en Finanzas",
    "Lic. en Bioinformática"
]